### ISSUE TITLE
Lots of deleted entities for a randomly picked part on Dassault Systems 3D content central

### ISSUE THREAD

**Issue by nickoe** [cbernardo/libIGES#1]
I just tested the readtest and I get a lot of deleted entities. This results in lots of shapes missing when reading the output in freecad.

     + [INFO] deleting Entity 124

The test model is from http://www.3dcontentcentral.com/Download-Model.aspx?catalogid=5730&id=558598

**Comment by cbernardo** [comment]
The library was rejecting valid curve entities due to a test which assures compliance with the IGES specification and the incomplete implementation of some curve entities. The test has been temporarily suppressed and the model is now handled correctly; the test will be enabled after there is more complete implementation of some curve entities.
