### ISSUE TITLE
Testing libIGES

### ISSUE THREAD

**Issue by ilockerstien** [cbernardo/libIGES#4]
Thanks for developing this.  It's going to be a VERY useful tool.
I'd love to test it out, but as a Kicad user (not developer), I'm not sure how to install it.  
Can you provide some brief instructions on how to install and run this program? (I'm running Ubuntu 14.04).

Thanks again!

**Comment by cbernardo** [comment]
I've added an "INSTALL" file to the main directory; it contains information on requirements, how to pull the git source, and the steps necessary to configure and build. Please try it out and let me know if there are any problems.

**Comment by ilockerstien** [comment]
I tried it out and I'm missing the 'patches' directory.  This has already been captured in a separate issue.

Thanks again!

**Comment by nickoe** [comment]
You should try to pull agian and retry the cmake command.

**Comment by ilockerstien** [comment]
Thanks for the instructions, it compiled and runs now.
I loaded the generated IGES file into Freecad and the board + hole locations are apparent, but the component geometries aren't shown.  In the original emn file, there appears to be two sections: BOARD_OUTLINE UNOWNED, and DRILLED_HOLES.  I suspect that the component geometry information should be in this file, but it's not readily apparent.

Is there something that needs to be enabled in Kicad to export component geometries to the emn file, or is this feature still under-development?

**Comment by cbernardo** [comment]
Unfortunately you will need to create component outlines as you need them; for a prettier board you can define all outlines, but from a practical point of view (mechanical fit check) you only need to define the most important parts. The documentation is currently scattered but people are working on fixing a number of issues and hopefully the coming kicad 'stable' release will include the documentation; in the meantime the original documentation (complete with mistakes) is here:

https://drive.google.com/open?id=0By_XTJN-s8aXbkM5UTE0Zm5SN28&authuser=0

There are not many people who need the IDF facility so there doesn't seem to be any interest in adding IDF component outlines to the KiCad libraries on github; however most professionals don't use the KiCad libraries anyway and just define their own parts.

For IGES things should improve in the future when the code is integrated with KiCad and IGES models supplied by manufacturers and retailers can be used. IDF will always be a bit of a nuisance, and I suspect once IGES export is included the use of IDF will almost disappear.

I have a sample IDF file for the PIC Programmer demo which includes component outlines; I was hoping to push all these into KiCad so that people can see actual examples of how to use the IDF exporter. See here:

https://drive.google.com/open?id=0By_XTJN-s8aXbkM5UTE0Zm5SN28&authuser=0

I did the same for the video board but haven't uploaded the files to google drive; however you can see the result here:

https://www.ecad.io/PCB/Show/example2

**Comment by ilockerstien** [comment]
Thanks, this is much clearer now.  I agree direct usage of IGES models into Kicad will greatly simplify 3D modeling.

Right now, I define my own parts library and convert from vendor IGES/STEP models to VRML, but I can't export this 3D model to 3D software such as Freecad, SolidWorks or Fusion360.  IGES export will greatly simply design iterations.

**Comment by cbernardo** [comment]
It's good to know other people use these tools; I get very little feedback on them even though these are essential tools for me. For mechanical work at the moment I would recommend using the IDF exporter since you get an exact mechanical representation of the bare board. However, MCAD packages like SolidWorks will not process IDF unless you paid extra for CircuitWorks (SW Professional or more expensive package); in such cases the idf2igs tool is useful since all professional MCAD packages support IGES import.
